<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KatiBayan - Dashboard</title>
  <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

  <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body>
  <div class="dashboard">
    
    <!-- Sidebar -->
    <aside class="sidebar">
  <button class="menu-toggle">Menu</button>
  <div class="divider"></div>
  <nav class="nav">
    <a href="#">
      <i data-lucide="layout-dashboard"></i>
      <span class="label">Dashboard</span>
    </a>
    <a href="#">
      <i data-lucide="circle-user"></i>
      <span class="label">Profile</span>
    </a>
    <a href="#">
      <i data-lucide="calendar"></i>
      <span class="label">Calendar</span>
    </a>
    <a href="#">
      <i data-lucide="megaphone"></i>
      <span class="label">Announcements</span>
    </a>
    <a href="#">
      <i data-lucide="settings"></i>
      <span class="label">Settings</span>
    </a>
  </nav>
</aside>


    <!-- Main -->
    <main class="main">
      
      <header class="topbar">
  <div class="logo">
    <img src="{{ asset('images/logo.png') }}" alt="Logo">
    <div class="logo-text">
      <span class="title">Katibayan</span>
      <span class="subtitle">Web Portal</span>
    </div>
  </div>

  <div class="topbar-right">
    <div class="search-box">
      <i data-lucide="search"></i>
      <input type="text" placeholder="Search something">
    </div>

    <div class="time">MON 10:00 <span>AM</span></div>
    <i class="fas fa-bell"></i>
    <img src="https://i.pravatar.cc/40" alt="User" class="avatar">
  </div>

</header>



      <!-- Row for Welcome + Calendar -->
<div class="row">
  <!-- Welcome -->
  <section class="welcome">
    <h2>Welcome, Marijoy!</h2>
    <h3>Have a nice day!</h3><br>
    <p> <span>KatiBayan</span> provides a platform for the youth to stay updated on SK events and programs while fostering active participation in community development.</p>
    
  </section>

  <div class="calendar">
  <header>
    <button class="prev"><i class="fas fa-chevron-left"></i></button>
    <h3></h3>
    <button class="next"><i class="fas fa-chevron-right"></i></button>
    <!-- Calendar icon upper-right -->
<i class="fas fa-calendar calendar-toggle" title="View full month"></i>

  </header>

  <!-- Weekdays + Dates generated by JS -->
  <div class="days"></div>
</div>



        <!-- Progress -->
<div class="progress">
  <h3>Your Progress</h3>
  <div class="progress-cards">
    
    <!-- Attendance -->
    <div class="card">
  <div class="card-content">
    <div class="text">
      <h4>Attendance</h4>
      <p>Monitor your progress</p>
    </div>
    <div class="icon">
      <i data-lucide="users"></i>
    </div>
  </div>

  <!-- Progress + Small sa iisang row -->
  <div class="progress-footer">
    <div class="bar"><span style="width:5%"></span></div>
    <small>5/100</small>
  </div>
</div>


    <!-- Evaluation -->
    <div class="card">
      <div class="card-content">
        <div class="text">
          <h4>Evaluation</h4>
          <p>You have 1 program to evaluate.</p>
        </div>
        <div class="icon">
          <i data-lucide="thumbs-up"></i>
        </div>
      </div>
      <small>0/1</small>
    </div>

    <!-- Poll -->
    <div class="card">
      <div class="card-content">
        <div class="text">
          <h4>Poll</h4>
          <p>Help shape our community.</p>
        </div>
        <div class="icon">
          <i data-lucide="bar-chart-3"></i>
        </div>
      </div>
      <a href="#">Join the poll →</a>
    </div>

  </div>
</div>

<!-- Events -->
  <div class="events-section">
  <!-- Title sa labas -->
  <h3 class="events-title">Upcoming Events</h3>

  <!-- White container -->
  <div class="events">
    <div class="events-top">
      <button class="events-menu">⋯</button>
    </div>

    <ul>
  <li>
    <span class="date">
      <strong>SEP</strong>
      <span>26</span>
    </span>
    <div class="event-info">
      <p>Anti-Rabbies Vaccine</p>
      <small>Upcoming</small>
    </div>
  </li>
  <li>
    <span class="date">
      <strong>OCT</strong>
      <span>02</span>
    </span>
    <div class="event-info">
      <p>KK Assembly</p>
      <small>Upcoming</small>
    </div>
  </li>
  <li>
    <span class="date">
      <strong>OCT</strong>
      <span>15</span>
    </span>
    <div class="event-info">
      <p>Baranggay Clean-up</p>
      <small>Upcoming</small>
    </div>
  </li>
</ul>


  </div>
</div>


<script src="https://unpkg.com/lucide@latest"></script>
<script>
  lucide.createIcons();
</script>

        <!-- Announcements -->
<div class="announcements-section">
  <!-- Title sa labas -->
  <h3 class="announcements-title">Announcements</h3>

  <!-- White container -->
  <div class="announcements">
    <div class="card">
      <div class="card-content">
        <div class="icon">
          <i class="fas fa-info"></i>
        </div>
        <div class="text">
          <strong>Important Announcement: No Office Today</strong>
          <p>The office is closed today. We sincerely apologize for any inconvenience.</p>
        </div>
      </div>
      <button class="options">⋯</button>
    </div>

    <div class="card">
      <div class="card-content">
        <div class="icon">
          <i class="fas fa-print"></i>
        </div>
        <div class="text">
          <strong>Notice: No Printing Service Today</strong>
          <p>Please be informed that printing services are closed today.</p>
        </div>
      </div>
      <button class="options">⋯</button>
    </div>

    <div class="card">
      <div class="card-content">
        <div class="icon">
          <i class="fas fa-print"></i>
        </div>
        <div class="text">
          <strong>Notice: No Printing Service Today</strong>
          <p>Please be informed that printing services are closed today.</p>
        </div>
      </div>
      <button class="options">⋯</button>
    </div>

    <div class="card">
      <div class="card-content">
        <div class="icon">
          <i class="fas fa-print"></i>
        </div>
        <div class="text">
          <strong>Notice: No Printing Service Today</strong>
          <p>Please be informed that printing services are closed today.</p>
        </div>
      </div>
      <button class="options">⋯</button>
    </div>

    <div class="card">
      <div class="card-content">
        <div class="icon">
          <i class="fas fa-print"></i>
        </div>
        <div class="text">
          <strong>Notice: No Printing Service Today</strong>
          <p>Please be informed that printing services are closed today.</p>
        </div>
      </div>
      <button class="options">⋯</button>
    </div>
  </div>
</div>



        <!-- Suggestion Box -->
        <div class="suggestion-box">
          <h2>Suggestion Box</h2>
          <p class="subtitle">You matter. Your voice counts.</p>

          <a href="#" class="suggestion-btn">
            Share with us <i class="fas fa-paper-plane"></i>
          </a>

          <p class="note">
            Everyone is encouraged to share their ideas and suggestions — we’re glad to hear from you!
          </p>
        </div>

      </div>

    </main>
  </div>

<script>
  // === For icons + sidebar ===
  lucide.createIcons();
  document.querySelector('.menu-toggle').addEventListener('click', () => {
    document.querySelector('.sidebar').classList.toggle('open');
  });

  // === Calendar Functionality ===
  document.addEventListener("DOMContentLoaded", () => {
    const weekdays = ["MON","TUE","WED","THU","FRI","SAT","SUN"];
    const daysContainer = document.querySelector(".calendar .days");
    const header = document.querySelector(".calendar header h3");

    let today = new Date();         // Current actual date
    let currentView = new Date();   // Controls what week we’re viewing

    function renderCalendar(baseDate) {
      daysContainer.innerHTML = "";

      // Compute start of week (Monday-first)
      const startOfWeek = new Date(baseDate);
      startOfWeek.setDate(baseDate.getDate() - (baseDate.getDay() === 0 ? 6 : baseDate.getDay() - 1));

      // Set header (Month + Year depends on middle day of the week)
      const middleDay = new Date(startOfWeek);
      middleDay.setDate(startOfWeek.getDate() + 3); // approx middle of the week
      const options = { month: "long", year: "numeric" };
      header.textContent = middleDay.toLocaleDateString("en-US", options);

      // Generate 7 days
      for (let i = 0; i < 7; i++) {
        const thisDay = new Date(startOfWeek);
        thisDay.setDate(startOfWeek.getDate() + i);

        const dayEl = document.createElement("div");
        dayEl.classList.add("day");

        // Highlight today (real date)
        if (
          thisDay.getDate() === today.getDate() &&
          thisDay.getMonth() === today.getMonth() &&
          thisDay.getFullYear() === today.getFullYear()
        ) {
          dayEl.classList.add("active");
        }

        const weekdayEl = document.createElement("span");
        weekdayEl.classList.add("weekday");
        weekdayEl.textContent = weekdays[i];

        const dateEl = document.createElement("span");
        dateEl.classList.add("date");
        dateEl.textContent = thisDay.getDate();

        dayEl.appendChild(weekdayEl);
        dayEl.appendChild(dateEl);
        daysContainer.appendChild(dayEl);
      }
    }

    // Initial render
    renderCalendar(currentView);

    // Buttons (prev / next week)
    document.querySelector(".calendar .prev").addEventListener("click", () => {
      currentView.setDate(currentView.getDate() - 7);
      renderCalendar(currentView);
    });

    document.querySelector(".calendar .next").addEventListener("click", () => {
      currentView.setDate(currentView.getDate() + 7);
      renderCalendar(currentView);
    });

    // === Time auto-update ===
    function updateTime() {
      const timeEl = document.querySelector(".time");
      if (!timeEl) return;

      const now = new Date();

      // Weekday short
      const shortWeekdays = ["SUN","MON","TUE","WED","THU","FRI","SAT"];
      const weekday = shortWeekdays[now.getDay()];

      // Hours + Minutes
      let hours = now.getHours();
      const minutes = now.getMinutes().toString().padStart(2, "0");
      const ampm = hours >= 12 ? "PM" : "AM";
      hours = hours % 12 || 12;

      // Format: MON 10:05 AM
      timeEl.innerHTML = `${weekday} ${hours}:${minutes} <span>${ampm}</span>`;
    }

    updateTime(); // initial load
    setInterval(updateTime, 60000); // update every 60s
  });
</script>



</body>
</html>
